AMP_ENABLE: False
MODEL:
  TYPE: revswin
  NAME: revswin_base_patch4_window7_224
  NICKNAME: B
  DROP_PATH_RATE: 0.5
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7