AMP_ENABLE: False
MODEL:
  TYPE: revswin
  NAME: revswin_giant_patch4_window7_224
  NICKNAME: G
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 512
    DEPTHS: [ 2, 2, 42, 2 ]
    NUM_HEADS: [ 16, 32, 64, 128 ]
    WINDOW_SIZE: 7
TRAIN:
  EPOCHS: 90
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05
  BASE_LR: 1.25e-4 # 4096 batch-size
  WARMUP_LR: 1.25e-7
  MIN_LR: 1.25e-6